### ISSUE TITLE
Setup priv-testnet to work with relay

### ISSUE THREAD

**Issue by ceseale** [polyswarm/priv-testnet#2]
**Is your feature request related to a problem? Please describe.**
This is related to adding relay to https://github.com/polyswarm/relay/issues/2

**Describe the solution you'd like**
We should get this working optionally with sealers so it can be relayed.

**Comment by ceseale** [comment]
Weirdly, this works locally and fails during contract migration on e2e master. In a e2e branch the shows all the docker-compose logs everything works for some reason.

truffle migrate failed master e2e branch:
https://gitlab.polyswarm.io/externalci/e2e/-/jobs/5485

truffle migrate working on feature/compose-logs e2e branch:
https://gitlab.polyswarm.io/externalci/e2e/-/jobs/5483

**Comment by scsich** [comment]
https://gitlab.polyswarm.io/externalci/e2e/commit/3cc4db40ddd93c1ed4fbbf6b8247dd15c037bf60
https://gitlab.polyswarm.io/externalci/e2e/commit/00689f9dd5040dcfb891e2f76b6e247f754b3320

2nd commit has log thread removed, not sure who/why.

**Comment by ceseale** [comment]
I was just using that to help debug. I needed to see the logs from all the services

**Comment by myhndl** [comment]
Where is this @ceseale ?

**Comment by Rizato** [comment]
I'm closing this. I think we are able to run e2e without any priv-testnet changes.
